### ISSUE TITLE
Improved error reporting

### ISSUE THREAD

**Issue by TheMaaarc** [luyadev/luya-module-forms#11]
### What steps will reproduce the problem?

1. Do something that is not allowed (for example a `-` in the attribute name #10)
2. This results in an internal server error that gets suppressed on prod environment
3. Customers that work with forms will only see "An internal server error occurred." but not the cause for the error

### What is the expected result?

A user-friendly message that can help a customer resolve the issue on his own.

**Comment by nadar** [comment]
This must be fixed by using a slug plugin which can take options like `delimiter`.

**Comment by nadar** [comment]
I am going to close this issue because:

- Its a question (Please post questions at [forum.luya.io](https://forum.luya.io))
- Missing information's
- No more activity
- No one picked up the task (no Pull Request received)

If you think this is still important or there are more/new informations. **Please reopen the issue and let us know**.

If this is a problem or a feature you like to discuss, join our forum: [forum.luya.io](https://forum.luya.io). We try to keep our issue tracker as clean as possible in order to focus on active issues.
